// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TunisiaStay.Data;

#nullable disable

namespace TunisiaStay.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260509224611_AddOffres")]
    partial class AddOffres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-role-id",
                            ConcurrencyStamp = "admin-role-id",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "user-role-id",
                            ConcurrencyStamp = "user-role-id",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TunisiaStay.Models.Amenite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Amenites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IconClass = "fa-wifi",
                            Nom = "WiFi Gratuit"
                        },
                        new
                        {
                            Id = 2,
                            IconClass = "fa-swimming-pool",
                            Nom = "Piscine"
                        },
                        new
                        {
                            Id = 3,
                            IconClass = "fa-parking",
                            Nom = "Parking"
                        },
                        new
                        {
                            Id = 4,
                            IconClass = "fa-snowflake",
                            Nom = "Climatisation"
                        },
                        new
                        {
                            Id = 5,
                            IconClass = "fa-utensils",
                            Nom = "Restaurant"
                        },
                        new
                        {
                            Id = 6,
                            IconClass = "fa-spa",
                            Nom = "Spa & Bien-être"
                        },
                        new
                        {
                            Id = 7,
                            IconClass = "fa-dumbbell",
                            Nom = "Salle de sport"
                        },
                        new
                        {
                            Id = 8,
                            IconClass = "fa-water",
                            Nom = "Vue mer"
                        },
                        new
                        {
                            Id = 9,
                            IconClass = "fa-coffee",
                            Nom = "Petit-déjeuner"
                        },
                        new
                        {
                            Id = 10,
                            IconClass = "fa-shuttle-van",
                            Nom = "Navette aéroport"
                        });
                });

            modelBuilder.Entity("TunisiaStay.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TunisiaStay.Models.Avis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Note")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("HotelId");

                    b.ToTable("Avis");
                });

            modelBuilder.Entity("TunisiaStay.Models.Chambre", b =>
                {
                    b.Property<int>("IdChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Etage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixParNuit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Surface")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdChambre");

                    b.HasIndex("HotelId");

                    b.ToTable("Chambres");

                    b.HasData(
                        new
                        {
                            IdChambre = 1,
                            Capacite = 2,
                            Description = "Chambre élégante avec vue sur les toits de la médina, décorée avec des zeliges authentiques et du mobilier en bois de thuya.",
                            Disponible = true,
                            Etage = 2,
                            HotelId = 1,
                            ImagePath = "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80",
                            Model = "Chambre Supérieure",
                            PrixParNuit = 180m,
                            Surface = 30
                        },
                        new
                        {
                            IdChambre = 2,
                            Capacite = 2,
                            Description = "Suite somptueuse avec salon privatif, baignoire balnéo et terrasse privée avec vue panoramique sur la vieille ville.",
                            Disponible = true,
                            Etage = 4,
                            HotelId = 1,
                            ImagePath = "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80",
                            Model = "Suite Deluxe",
                            PrixParNuit = 350m,
                            Surface = 55
                        },
                        new
                        {
                            IdChambre = 3,
                            Capacite = 4,
                            Description = "L'apogée du luxe tunisien. Deux chambres, grand salon, salle à manger privée et terrasse panoramique avec jacuzzi extérieur.",
                            Disponible = true,
                            Etage = 6,
                            HotelId = 1,
                            ImagePath = "https://images.unsplash.com/photo-1591088398332-8596b4c8b4c5?w=800&q=80",
                            Model = "Suite Présidentielle",
                            PrixParNuit = 950m,
                            Surface = 130
                        },
                        new
                        {
                            IdChambre = 4,
                            Capacite = 2,
                            Description = "Chambre lumineuse avec balcon privé et vue directe sur la Méditerranée. Décoration épurée aux tons blancs et bleus.",
                            Disponible = true,
                            Etage = 1,
                            HotelId = 2,
                            ImagePath = "https://images.unsplash.com/photo-1615460549969-36fa19521a4f?w=800&q=80",
                            Model = "Chambre Vue Mer",
                            PrixParNuit = 260m,
                            Surface = 38
                        },
                        new
                        {
                            IdChambre = 5,
                            Capacite = 3,
                            Description = "Bungalow exclusif avec accès direct à la plage privée. Terrasse, salon extérieur et piscine à débordement personnelle.",
                            Disponible = true,
                            Etage = 0,
                            HotelId = 2,
                            ImagePath = "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800&q=80",
                            Model = "Bungalow Plage",
                            PrixParNuit = 520m,
                            Surface = 70
                        },
                        new
                        {
                            IdChambre = 6,
                            Capacite = 2,
                            Description = "Chambre deluxe avec balcon et vue sur la piscine et la mer. Équipements haut de gamme et literie premium.",
                            Disponible = true,
                            Etage = 3,
                            HotelId = 3,
                            ImagePath = "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80",
                            Model = "Chambre Deluxe",
                            PrixParNuit = 210m,
                            Surface = 35
                        },
                        new
                        {
                            IdChambre = 7,
                            Capacite = 2,
                            Description = "Suite junior avec vue mer panoramique, coin salon séparé et salle de bain en marbre avec douche à l'italienne.",
                            Disponible = true,
                            Etage = 5,
                            HotelId = 3,
                            ImagePath = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
                            Model = "Suite Junior",
                            PrixParNuit = 320m,
                            Surface = 50
                        },
                        new
                        {
                            IdChambre = 8,
                            Capacite = 2,
                            Description = "Chambre confortable et bien équipée avec vue sur le jardin. Idéale pour un séjour ensoleillé à Hammamet.",
                            Disponible = true,
                            Etage = 1,
                            HotelId = 4,
                            ImagePath = "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80",
                            Model = "Chambre Standard",
                            PrixParNuit = 140m,
                            Surface = 26
                        },
                        new
                        {
                            IdChambre = 9,
                            Capacite = 4,
                            Description = "Chambre spacieuse pour familles avec deux lits doubles, espace jeux et balcon donnant sur l'orangeraie.",
                            Disponible = true,
                            Etage = 2,
                            HotelId = 4,
                            ImagePath = "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&q=80",
                            Model = "Chambre Familiale",
                            PrixParNuit = 240m,
                            Surface = 48
                        });
                });

            modelBuilder.Entity("TunisiaStay.Models.ChambreAmenite", b =>
                {
                    b.Property<int>("ChambreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmeniteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChambreId", "AmeniteId");

                    b.HasIndex("AmeniteId");

                    b.ToTable("ChambreAmenites");

                    b.HasData(
                        new
                        {
                            ChambreId = 1,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 1,
                            AmeniteId = 4
                        },
                        new
                        {
                            ChambreId = 1,
                            AmeniteId = 9
                        },
                        new
                        {
                            ChambreId = 2,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 2,
                            AmeniteId = 4
                        },
                        new
                        {
                            ChambreId = 2,
                            AmeniteId = 6
                        },
                        new
                        {
                            ChambreId = 2,
                            AmeniteId = 9
                        },
                        new
                        {
                            ChambreId = 3,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 3,
                            AmeniteId = 2
                        },
                        new
                        {
                            ChambreId = 3,
                            AmeniteId = 4
                        },
                        new
                        {
                            ChambreId = 3,
                            AmeniteId = 5
                        },
                        new
                        {
                            ChambreId = 3,
                            AmeniteId = 6
                        },
                        new
                        {
                            ChambreId = 4,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 4,
                            AmeniteId = 4
                        },
                        new
                        {
                            ChambreId = 4,
                            AmeniteId = 8
                        },
                        new
                        {
                            ChambreId = 5,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 5,
                            AmeniteId = 2
                        },
                        new
                        {
                            ChambreId = 5,
                            AmeniteId = 8
                        },
                        new
                        {
                            ChambreId = 5,
                            AmeniteId = 6
                        },
                        new
                        {
                            ChambreId = 6,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 6,
                            AmeniteId = 4
                        },
                        new
                        {
                            ChambreId = 6,
                            AmeniteId = 9
                        },
                        new
                        {
                            ChambreId = 7,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 7,
                            AmeniteId = 4
                        },
                        new
                        {
                            ChambreId = 7,
                            AmeniteId = 8
                        },
                        new
                        {
                            ChambreId = 7,
                            AmeniteId = 6
                        },
                        new
                        {
                            ChambreId = 8,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 8,
                            AmeniteId = 4
                        },
                        new
                        {
                            ChambreId = 8,
                            AmeniteId = 3
                        },
                        new
                        {
                            ChambreId = 9,
                            AmeniteId = 1
                        },
                        new
                        {
                            ChambreId = 9,
                            AmeniteId = 4
                        },
                        new
                        {
                            ChambreId = 9,
                            AmeniteId = 3
                        },
                        new
                        {
                            ChambreId = 9,
                            AmeniteId = 9
                        });
                });

            modelBuilder.Entity("TunisiaStay.Models.Client", b =>
                {
                    b.Property<int>("ClientKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numéro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prénom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Telephone")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientKey");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TunisiaStay.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumContact")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "15 Avenue Habib Bourguiba, Tunis 1000",
                            City = "Tunis",
                            Classification = "5 étoiles",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Niché au cœur de la médina historique de Tunis, cet établissement d'exception marie l'architecture arabo-andalouse authentique avec le luxe contemporain. Classé patrimoine architectural, il offre une expérience unique entre souks et modernité.",
                            Email = "contact@medina-tunis.tn",
                            ImagePath = "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80",
                            IsActive = true,
                            Latitude = 36.818899999999999,
                            Longitude = 10.165800000000001,
                            Name = "Hôtel La Médina Tunis",
                            NumContact = 71234567
                        },
                        new
                        {
                            Id = 2,
                            Address = "Zone Touristique Sidi Mahrez, Djerba",
                            City = "Djerba",
                            Classification = "5 étoiles",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Resort de luxe face à la mer Méditerranée, sur l'île enchanteresse de Djerba. Plage privée de sable blanc, centre de thalassothérapie primé et gastronomie raffinée vous attendent dans un cadre paradisiaque.",
                            Email = "reservation@hasdrubal-djerba.tn",
                            ImagePath = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80",
                            IsActive = true,
                            Latitude = 33.807499999999997,
                            Longitude = 10.8451,
                            Name = "Hasdrubal Thalassa & Spa Djerba",
                            NumContact = 75609000
                        },
                        new
                        {
                            Id = 3,
                            Address = "Boulevard de la Corniche, Sousse 4000",
                            City = "Sousse",
                            Classification = "5 étoiles",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Véritable palace sur la corniche de Sousse, avec vue imprenable sur la Méditerranée. Ses jardins luxuriants, sa grande piscine et ses suites panoramiques en font la destination idéale pour un séjour de prestige.",
                            Email = "info@marhaba-sousse.tn",
                            ImagePath = "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80",
                            IsActive = true,
                            Latitude = 35.828800000000001,
                            Longitude = 10.635,
                            Name = "Marhaba Palace Sousse",
                            NumContact = 73227700
                        },
                        new
                        {
                            Id = 4,
                            Address = "Avenue des Hôtels, Hammamet 8050",
                            City = "Hammamet",
                            Classification = "4 étoiles",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hôtel de charme à Hammamet, la Côte d'Azur tunisienne. Entre orangeraies parfumées et plages de sable fin, Le Sindbad propose une expérience authentique dans un cadre verdoyant et apaisé.",
                            Email = "contact@sindbad-hammamet.tn",
                            ImagePath = "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
                            IsActive = true,
                            Latitude = 36.3992,
                            Longitude = 10.5664,
                            Name = "The Sindbad Hammamet",
                            NumContact = 72280100
                        });
                });

            modelBuilder.Entity("TunisiaStay.Models.Offre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChambreIdChambre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pourcentage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChambreIdChambre");

                    b.HasIndex("HotelId");

                    b.ToTable("Offres");
                });

            modelBuilder.Entity("TunisiaStay.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Méthode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("TunisiaStay.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChambreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Durée")
                        .HasColumnType("REAL");

                    b.Property<double>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("En attente");

                    b.HasKey("Id");

                    b.HasIndex("ChambreId");

                    b.HasIndex("ClientId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TunisiaStay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TunisiaStay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunisiaStay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TunisiaStay.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TunisiaStay.Models.Avis", b =>
                {
                    b.HasOne("TunisiaStay.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunisiaStay.Models.Hotel", "Hotel")
                        .WithMany("Avis")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TunisiaStay.Models.Chambre", b =>
                {
                    b.HasOne("TunisiaStay.Models.Hotel", "Hotel")
                        .WithMany("Chambres")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TunisiaStay.Models.ChambreAmenite", b =>
                {
                    b.HasOne("TunisiaStay.Models.Amenite", "Amenite")
                        .WithMany("ChambreAmenites")
                        .HasForeignKey("AmeniteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunisiaStay.Models.Chambre", "Chambre")
                        .WithMany("ChambreAmenites")
                        .HasForeignKey("ChambreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenite");

                    b.Navigation("Chambre");
                });

            modelBuilder.Entity("TunisiaStay.Models.Client", b =>
                {
                    b.HasOne("TunisiaStay.Models.ApplicationUser", "ApplicationUser")
                        .WithOne("Client")
                        .HasForeignKey("TunisiaStay.Models.Client", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TunisiaStay.Models.Hotel", b =>
                {
                    b.HasOne("TunisiaStay.Models.ApplicationUser", "Owner")
                        .WithMany("OwnedHotels")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TunisiaStay.Models.Offre", b =>
                {
                    b.HasOne("TunisiaStay.Models.Chambre", null)
                        .WithMany("Offres")
                        .HasForeignKey("ChambreIdChambre");

                    b.HasOne("TunisiaStay.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TunisiaStay.Models.Paiement", b =>
                {
                    b.HasOne("TunisiaStay.Models.Reservation", "Reservation")
                        .WithOne("Paiement")
                        .HasForeignKey("TunisiaStay.Models.Paiement", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("TunisiaStay.Models.Reservation", b =>
                {
                    b.HasOne("TunisiaStay.Models.Chambre", "Chambre")
                        .WithMany("Reservations")
                        .HasForeignKey("ChambreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TunisiaStay.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chambre");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TunisiaStay.Models.Amenite", b =>
                {
                    b.Navigation("ChambreAmenites");
                });

            modelBuilder.Entity("TunisiaStay.Models.ApplicationUser", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("OwnedHotels");
                });

            modelBuilder.Entity("TunisiaStay.Models.Chambre", b =>
                {
                    b.Navigation("ChambreAmenites");

                    b.Navigation("Offres");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TunisiaStay.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TunisiaStay.Models.Hotel", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Chambres");
                });

            modelBuilder.Entity("TunisiaStay.Models.Reservation", b =>
                {
                    b.Navigation("Paiement");
                });
#pragma warning restore 612, 618
        }
    }
}
